# Reading data from CSVs 

In [ ]:
!python -m pip install pandas

import pandas as pd

movies_df = pd.read_csv("IMDB-Movie-Data.csv", index_col="Title") 

read_csv reads the csv file and index_col = "Title" sets the column name of the default indexing as title

# Viewing your data 

In [ ]:
movies_df.head()
movies_df.shape

head() returns the top rows (top 5 rows by default) elements of the data

shape return the no. of rows and columns of the dataset in the format (row, column)

# Program 1

In [8]:
# !python -m pip install pandas

import pandas as pd

S = pd.Series([11, 28, 72, 3, 5, 8])
S

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64

# Program 2

In [9]:
print(S.index)
print(S.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]


# Program 3

In [11]:
# !python -m pip install numpy

import numpy as np
X= np.array([11,28,72,3,5,8])
print(X)
print(S.values)
print(type(S.values), type(X))

[11 28 72  3  5  8]
[11 28 72  3  5  8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# Program 4

In [12]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
quantities = [20, 33, 52, 10]
S = pd.Series (quantities, index=fruits)
S

apples      20
oranges     33
cherries    52
pears       10
dtype: int64

index = fruits sets the default index values (0,1,2,...) as the elements of the list fruits

# Program 5

In [13]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
S = pd.Series ([20, 33, 52, 10], index=fruits)
S2 = pd.Series ([17, 13, 31, 32], index=fruits)
print (S + S2)
print ("sum of S: ", sum (S))

apples      37
oranges     46
cherries    83
pears       42
dtype: int64
sum of S:  115


If we add two series with the same indices, we get a new series with the same index and the corresponding values will be added

# Program 6

In [14]:
fruits = ['peaches', 'oranges', 'cherries', 'pears']
fruits2 = ['raspberries', 'oranges', 'cherries', 'pears']
S = pd.Series ([20, 33, 52, 10], index=fruits)
S2 = pd.Series ([17, 13, 31, 32], index=fruits2)
print (S + S2)

cherries       83.0
oranges        46.0
peaches         NaN
pears          42.0
raspberries     NaN
dtype: float64


The indices do not have to be the same for the Series addition. The index will be the "union" of both indices. If an index doesn't occur in both Series, the value for this Series will be NaN.

# Program 7

In [15]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
fruits_tr = ['elma', 'portakal', 'kiraz', 'armut']
S = pd.Series ([20, 33, 52, 10], index=fruits)
S2 = pd.Series ([17, 13, 31, 32], index=fruits_tr)
print (S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


In principle, the indices can be completely different, as in the following example. We have two indices. One is the Turkish translation of the English fruit names.

# Program 8 - Indexing

In [16]:
print (S['apples'])

20
